
SELECT * FROM tblEmployee
SELECT * FROM tblDepartment

-- QUE 1.SELECT TOP MOST SALARY FROM THE TABLE EMPLOYEE

SELECT TOP 1  NAME, ID,SALARY FROM tblEmployee
ORDER BY Salary DESC
--OR
SELECT * FROM tblEmployee 
WHERE SALARY=(SELECT MAX(SALARY) FROM tblEmployee)


--QUE 2. SELECT 2ND HIGHEST SALARY

SELECT MAX(SALARY) 
FROM tblEmployee 
WHERE Salary NOT IN (SELECT MAX(Salary) FROM tblEmployee)

--QUE 3. SELECT RANGE OF EMPLOYEE BASED ON EMPLOYEE ID(BETWEEN)

SELECT * FROM tblEmployee
WHERE ID BETWEEN 2 AND  8


--QUE 4. RETURN NAME, HIGHEST SALARY AND DEPARTMENT (inner join)
SELECT NAME, E.ID,E.Salary, D.DEPARTMENTNAME FROM tblEmployee E
INNER JOIN tblDepartment D ON (E.DepartmentID=D.ID)
WHERE SALARY = (SELECT MAX(SALARY) FROM tblEmployee) 


--QUE 5. RETURN NAME, HIGHEST SALARY from each department AND DEPARTMENT (inner join)
SELECT NAME, E.ID,E.Salary, D.DEPARTMENTNAME FROM tblEmployee E
INNER JOIN tblDepartment D ON (E.DepartmentID=D.ID)
WHERE Salary IN (SELECT MAX(Salary) FROM tblEmployee GROUP BY DepartmentID)







